### ISSUE TITLE
No View Statistics in 5.2.4

### ISSUE THREAD

**Issue by SPHolzi** [kartolo/direct_mail#185]
After the update to 5.2.4 the HTML Views in the statistics are no more calculated, the dmailerping.gif is still included as it was before.

Regards Steffen

**Comment by kartolo** [comment]
can't reproduce this. how do you include the dmailerping.gif?

**Comment by SPHolzi** [comment]
Hi Ivan,

thanks for that quick response. It is included as a image reference to the Page itself with a jumpurl to the dmailerping.gif. This worked fine all the time and stopped working just as we updated to 5.2.4.

`<img src="http://DOMAIN/index.php?id=pid&amp;rid=t_20783865&amp;mid=1706&amp;aC=87dadec5&amp;jumpurl=http://DOMAIN/typo3conf/ext/direct_mail/Resources/Public/Icons/dmailerping.gif" width="1" height="1" dmailerping="1">`

**Comment by kartolo** [comment]
because the dmailerping.gif is linked using an absolute URL, it's not counted. The [last security fix](5f9774a3065fb2a16c0e7fa6bd4a598f99210a94), is prohibiting http(s) URL in the jumpurl parameter. 

Please embed the dmailerping.gif without the domain, only `/typo3conf/ext/direct_mail/Resources/Public/Icons/dmailerping.gif`

**Comment by dvoigt** [comment]
> Please embed the dmailerping.gif without the domain

It's not working here since 5.2.4. either, and we're not using jumpurl for the gif. 

The domain is being added to all paths automatically when sending out a mail. It has to be. Just like any other image that's located on the sender's server. Without a domain added, the email client will not find the file, because it's not local.
