### ISSUE TITLE
What exactly does the setting "Interval of the cronjob" do?

### ISSUE THREAD

**Issue by rowild** [kartolo/direct_mail#200]
The provided setting of the "Direct Mail: Mailing Queue" already provides a time interval. The above mentioned settings provide an option to set an additional interval. What is it good for? How does it relate to the cron task?

In my case, being on a shared hosting (without shell access), I need my own php script (calling the TYPO3 scheduler):

```
<?php
exec("php73 /www/htdocs/USER/PATH/typo3/sysext/core/bin/typo3 scheduler:run 3>&1", $out, $result);
```

(where "3" is the uid of the "Direct Mail: Mailing Queue" scheduler task). The script is registered as a cron job via the hoster's backend options and is set to be executed every minute (1 min). So I end up with 3 things that need somehow to be aligned - and I have no idea how:

Server: 1min
DirectMail's Cron Task in TYPO3: 10min
DirectMail's Extension Setting: ????

Any Idea how to configure these things correctly?
Any chance of more explanation concerning the above mentioned feature and maybe examples for how to best configure it?

Thank you!

**Comment by kartolo** [comment]
The setting "Interval of the cronjob" is ancient :( it was added before there was Scheduler module in TYPO3. It's used check if the Mailer Engine is run and will show in the Mailer Engine module if it's late.

with the Scheduler task, you should set the timing in Scheduler Task, and call the Scheduler CLI often.

So if you set your scheduler script every minute, and direct mail in scheduler task every 5 minutes, then you can set the setting to 5 minutes. If you set every minute in direct mail setting, then in the mailer engine module will be shown that the engine is late.

Maybe it's best to remove this, since you can directly check the scheduler module, if the task is run or there's failure.

**Comment by lorenzulrich** [comment]
I would also be in favor of removing this.

**Comment by SSFGizmo** [comment]
reminder

```
$cronInterval = Typo3ConfVarsUtility::getDMConfigCronInt() * 60;
$lastCronjobShouldBeNewThan = (time() - $cronInterval);
```

**Comment by SSFGizmo** [comment]
I have removed the part with the interval
v.9.2.0
