### ISSUE TITLE
cant delete scheduled and not running mailings

### ISSUE THREAD

**Issue by ThomasSeifert01** [kartolo/direct_mail#244]
reason why:
direct_mail/Classes/Module/MailerEngine.php

Line: 459

Codechange
From:
if (!$dmail['scheduled_begin']) { .....}

To
if (!empty($dmail['scheduled_begin'])) { .... }

in V9.5

**Comment by xperseguers** [comment]
A bit unsure about the explanation of @ThomasSeifert01 but it seems I face the same problem.

## Context

* An editor scheduled a newsletter to be sent in 1 hour
* He figures out there's something he want to change so he wants to cancel the sending
* He opens the Mailer Engine module and sees his scheduled newsletter but there's no delete icon since (as pointed out in this ticket) the link is only shown if the newsletter started being sent

I'm unsure about the explanation of the `!` having been changed into a `!empty()` but please ensure a scheduled newsletter can actually be dropped.

**Comment by kartolo** [comment]
The timestamp when the mailing is started (or ended) are saved in `scheduled_begin ` (and `scheduled_end`. Default value is a `0`. The code has to be changed from `!empty()`, to `!`. But this only covers, if the newsletter hasn't been sent. Once the newsletter is started sending, `scheduled_begin` is set `>0` and `scheduled_end` is 0. 

The code has to be improved.

**Comment by kartolo** [comment]
the fix is added to branch 6.0 (TYPO3 9 LTS only) and develop (10 LTS)

**Comment by joeschi** [comment]
I have now noticed that you can't delete already sent mails in the module. For this the code line in MailerEngine.php should read:
` 469:       if (!($dmail['scheduled_begin']) ||
            ($dmail['scheduled_begin'] && $dmail['scheduled_end'] > 0)) {
`
